# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
  - port: 8181
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      sudo docker-up &
      mkdir -p /workspace/pgadmin-data
      sudo chown -R 5050:5050 /workspace/pgadmin-data
      sleep 5
    init: docker-compose up --no-start
    command: docker-compose up -d
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-lombok
    - eamodio.gitlens
    - felipecaputo.git-project-manager
    - dbaeumer.vscode-eslint
    - ms-vscode.cpptools-extension-pack
    - evondev.indent-rainbow-palettes
    - donjayamanne.git-extension-pack
    - esbenp.prettier-vscode
    - redhat.vscode-xml
    - rangav.vscode-thunder-client
    - developersoapbox.vscode-springboot-developer-pack
    - ms-azuretools.vscode-dapr
    - bierner.markdown-preview-github-styles
    - oderwat.indent-rainbow
    - cweijan.git-graph-history
    - mhutchie.git-graph
    - ms-vscode.makefile-tools
    - mongodb.mongodb-vscode 
