server:
    port: 8090
spring:
    application:
        name: edge-service
# Service discovery configs
eureka:
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
        prefer-ip-address: true
    client:
        healthcheck.enabled: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
        initial-instance-info-replication-interval-seconds: 5
        registry-fetch-interval-seconds: 5