server:
    port: 7001
    error:
        include-message: always
spring:
    application:
        name: user-service
    data:
        mongodb:
        #mongo:
            uri: mongodb+srv
            #username: root
            #password: example
            #host: localhost
            #port: 27017
            #database: user-db
            #authentication-database: testdb
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest
    # Messaging binders for the cloud streaming
    cloud:
        stream:
            default-binder: rabbit
            # contentType: application/json
            bindings:
                input: # Use the function name as used below
                    destination: users
                    group: usersGroup
                    contentType: application/json
                # Use the consumer function name as input 
                # to create destination and group in 3.0+
                userConsumer-in-0:
                    destination: users
                    group: usersGroup
            # Consumer input binding parameters
                    consumer:
                        maxAttempts: 3
                        backOffInitialInterval: 500
                        backOffMaxInterval: 1000
                        backOffMultiplier: 2.0
            # RabbitMQ consumer input binding parameters
            rabbit:
                bindings:
                    userConsumer-in-0:
                        consumer:
                            auto-bind-dlq: true
                            republishToDlq: true
            kafka:
                bindings:
                    userConsumer-in-0:
                        consumer:
                            autoBindDlq: true
                            republishToDlq: true
                # binder:
                    brokers: 127.0.0.1
                    defaultBrokerPort: 9092


management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                exclude: "*"